blank_issues_enabled: false
contact_links:
  - name: AllThingsNix  Support
    url: mailto: allthingsnix.org@gmail.com
    about: Contact Support if you're having trouble with any allthingsnix products 
